// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clockSync.proto

package io.grpc.clockSync;

public final class ClockSync {
  private ClockSync() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface reqTimeObjOrBuilder extends
      // @@protoc_insertion_point(interface_extends:reqTimeObj)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string client_sent_time = 1;</code>
     */
    java.lang.String getClientSentTime();
    /**
     * <code>string client_sent_time = 1;</code>
     */
    com.google.protobuf.ByteString
        getClientSentTimeBytes();
  }
  /**
   * Protobuf type {@code reqTimeObj}
   */
  public  static final class reqTimeObj extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:reqTimeObj)
      reqTimeObjOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use reqTimeObj.newBuilder() to construct.
    private reqTimeObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private reqTimeObj() {
      clientSentTime_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private reqTimeObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              clientSentTime_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.clockSync.ClockSync.internal_static_reqTimeObj_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.clockSync.ClockSync.internal_static_reqTimeObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.clockSync.ClockSync.reqTimeObj.class, io.grpc.clockSync.ClockSync.reqTimeObj.Builder.class);
    }

    public static final int CLIENT_SENT_TIME_FIELD_NUMBER = 1;
    private volatile java.lang.Object clientSentTime_;
    /**
     * <code>string client_sent_time = 1;</code>
     */
    public java.lang.String getClientSentTime() {
      java.lang.Object ref = clientSentTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientSentTime_ = s;
        return s;
      }
    }
    /**
     * <code>string client_sent_time = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientSentTimeBytes() {
      java.lang.Object ref = clientSentTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientSentTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClientSentTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientSentTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClientSentTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientSentTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.grpc.clockSync.ClockSync.reqTimeObj)) {
        return super.equals(obj);
      }
      io.grpc.clockSync.ClockSync.reqTimeObj other = (io.grpc.clockSync.ClockSync.reqTimeObj) obj;

      boolean result = true;
      result = result && getClientSentTime()
          .equals(other.getClientSentTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENT_SENT_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getClientSentTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.grpc.clockSync.ClockSync.reqTimeObj parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.clockSync.ClockSync.reqTimeObj parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.clockSync.ClockSync.reqTimeObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.clockSync.ClockSync.reqTimeObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.clockSync.ClockSync.reqTimeObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.clockSync.ClockSync.reqTimeObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.clockSync.ClockSync.reqTimeObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.clockSync.ClockSync.reqTimeObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.clockSync.ClockSync.reqTimeObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.grpc.clockSync.ClockSync.reqTimeObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.clockSync.ClockSync.reqTimeObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.clockSync.ClockSync.reqTimeObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.grpc.clockSync.ClockSync.reqTimeObj prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code reqTimeObj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:reqTimeObj)
        io.grpc.clockSync.ClockSync.reqTimeObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.grpc.clockSync.ClockSync.internal_static_reqTimeObj_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.grpc.clockSync.ClockSync.internal_static_reqTimeObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.grpc.clockSync.ClockSync.reqTimeObj.class, io.grpc.clockSync.ClockSync.reqTimeObj.Builder.class);
      }

      // Construct using io.grpc.clockSync.ClockSync.reqTimeObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        clientSentTime_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.grpc.clockSync.ClockSync.internal_static_reqTimeObj_descriptor;
      }

      @java.lang.Override
      public io.grpc.clockSync.ClockSync.reqTimeObj getDefaultInstanceForType() {
        return io.grpc.clockSync.ClockSync.reqTimeObj.getDefaultInstance();
      }

      @java.lang.Override
      public io.grpc.clockSync.ClockSync.reqTimeObj build() {
        io.grpc.clockSync.ClockSync.reqTimeObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.grpc.clockSync.ClockSync.reqTimeObj buildPartial() {
        io.grpc.clockSync.ClockSync.reqTimeObj result = new io.grpc.clockSync.ClockSync.reqTimeObj(this);
        result.clientSentTime_ = clientSentTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.grpc.clockSync.ClockSync.reqTimeObj) {
          return mergeFrom((io.grpc.clockSync.ClockSync.reqTimeObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.grpc.clockSync.ClockSync.reqTimeObj other) {
        if (other == io.grpc.clockSync.ClockSync.reqTimeObj.getDefaultInstance()) return this;
        if (!other.getClientSentTime().isEmpty()) {
          clientSentTime_ = other.clientSentTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.grpc.clockSync.ClockSync.reqTimeObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.grpc.clockSync.ClockSync.reqTimeObj) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object clientSentTime_ = "";
      /**
       * <code>string client_sent_time = 1;</code>
       */
      public java.lang.String getClientSentTime() {
        java.lang.Object ref = clientSentTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientSentTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string client_sent_time = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClientSentTimeBytes() {
        java.lang.Object ref = clientSentTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientSentTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client_sent_time = 1;</code>
       */
      public Builder setClientSentTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientSentTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client_sent_time = 1;</code>
       */
      public Builder clearClientSentTime() {
        
        clientSentTime_ = getDefaultInstance().getClientSentTime();
        onChanged();
        return this;
      }
      /**
       * <code>string client_sent_time = 1;</code>
       */
      public Builder setClientSentTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientSentTime_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:reqTimeObj)
    }

    // @@protoc_insertion_point(class_scope:reqTimeObj)
    private static final io.grpc.clockSync.ClockSync.reqTimeObj DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.grpc.clockSync.ClockSync.reqTimeObj();
    }

    public static io.grpc.clockSync.ClockSync.reqTimeObj getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<reqTimeObj>
        PARSER = new com.google.protobuf.AbstractParser<reqTimeObj>() {
      @java.lang.Override
      public reqTimeObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new reqTimeObj(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<reqTimeObj> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<reqTimeObj> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.grpc.clockSync.ClockSync.reqTimeObj getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface resTimeObjOrBuilder extends
      // @@protoc_insertion_point(interface_extends:resTimeObj)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string client_sent_time = 1;</code>
     */
    java.lang.String getClientSentTime();
    /**
     * <code>string client_sent_time = 1;</code>
     */
    com.google.protobuf.ByteString
        getClientSentTimeBytes();

    /**
     * <code>string server_recd_time = 2;</code>
     */
    java.lang.String getServerRecdTime();
    /**
     * <code>string server_recd_time = 2;</code>
     */
    com.google.protobuf.ByteString
        getServerRecdTimeBytes();

    /**
     * <code>string server_sent_time = 3;</code>
     */
    java.lang.String getServerSentTime();
    /**
     * <code>string server_sent_time = 3;</code>
     */
    com.google.protobuf.ByteString
        getServerSentTimeBytes();
  }
  /**
   * Protobuf type {@code resTimeObj}
   */
  public  static final class resTimeObj extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:resTimeObj)
      resTimeObjOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use resTimeObj.newBuilder() to construct.
    private resTimeObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private resTimeObj() {
      clientSentTime_ = "";
      serverRecdTime_ = "";
      serverSentTime_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private resTimeObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              clientSentTime_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              serverRecdTime_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              serverSentTime_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.clockSync.ClockSync.internal_static_resTimeObj_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.clockSync.ClockSync.internal_static_resTimeObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.clockSync.ClockSync.resTimeObj.class, io.grpc.clockSync.ClockSync.resTimeObj.Builder.class);
    }

    public static final int CLIENT_SENT_TIME_FIELD_NUMBER = 1;
    private volatile java.lang.Object clientSentTime_;
    /**
     * <code>string client_sent_time = 1;</code>
     */
    public java.lang.String getClientSentTime() {
      java.lang.Object ref = clientSentTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientSentTime_ = s;
        return s;
      }
    }
    /**
     * <code>string client_sent_time = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientSentTimeBytes() {
      java.lang.Object ref = clientSentTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientSentTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVER_RECD_TIME_FIELD_NUMBER = 2;
    private volatile java.lang.Object serverRecdTime_;
    /**
     * <code>string server_recd_time = 2;</code>
     */
    public java.lang.String getServerRecdTime() {
      java.lang.Object ref = serverRecdTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverRecdTime_ = s;
        return s;
      }
    }
    /**
     * <code>string server_recd_time = 2;</code>
     */
    public com.google.protobuf.ByteString
        getServerRecdTimeBytes() {
      java.lang.Object ref = serverRecdTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverRecdTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVER_SENT_TIME_FIELD_NUMBER = 3;
    private volatile java.lang.Object serverSentTime_;
    /**
     * <code>string server_sent_time = 3;</code>
     */
    public java.lang.String getServerSentTime() {
      java.lang.Object ref = serverSentTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverSentTime_ = s;
        return s;
      }
    }
    /**
     * <code>string server_sent_time = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServerSentTimeBytes() {
      java.lang.Object ref = serverSentTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverSentTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClientSentTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientSentTime_);
      }
      if (!getServerRecdTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serverRecdTime_);
      }
      if (!getServerSentTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, serverSentTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClientSentTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientSentTime_);
      }
      if (!getServerRecdTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, serverRecdTime_);
      }
      if (!getServerSentTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, serverSentTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.grpc.clockSync.ClockSync.resTimeObj)) {
        return super.equals(obj);
      }
      io.grpc.clockSync.ClockSync.resTimeObj other = (io.grpc.clockSync.ClockSync.resTimeObj) obj;

      boolean result = true;
      result = result && getClientSentTime()
          .equals(other.getClientSentTime());
      result = result && getServerRecdTime()
          .equals(other.getServerRecdTime());
      result = result && getServerSentTime()
          .equals(other.getServerSentTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CLIENT_SENT_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getClientSentTime().hashCode();
      hash = (37 * hash) + SERVER_RECD_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getServerRecdTime().hashCode();
      hash = (37 * hash) + SERVER_SENT_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getServerSentTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.grpc.clockSync.ClockSync.resTimeObj parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.clockSync.ClockSync.resTimeObj parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.clockSync.ClockSync.resTimeObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.clockSync.ClockSync.resTimeObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.clockSync.ClockSync.resTimeObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.clockSync.ClockSync.resTimeObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.clockSync.ClockSync.resTimeObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.clockSync.ClockSync.resTimeObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.clockSync.ClockSync.resTimeObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.grpc.clockSync.ClockSync.resTimeObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.clockSync.ClockSync.resTimeObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.clockSync.ClockSync.resTimeObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.grpc.clockSync.ClockSync.resTimeObj prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code resTimeObj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:resTimeObj)
        io.grpc.clockSync.ClockSync.resTimeObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.grpc.clockSync.ClockSync.internal_static_resTimeObj_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.grpc.clockSync.ClockSync.internal_static_resTimeObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.grpc.clockSync.ClockSync.resTimeObj.class, io.grpc.clockSync.ClockSync.resTimeObj.Builder.class);
      }

      // Construct using io.grpc.clockSync.ClockSync.resTimeObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        clientSentTime_ = "";

        serverRecdTime_ = "";

        serverSentTime_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.grpc.clockSync.ClockSync.internal_static_resTimeObj_descriptor;
      }

      @java.lang.Override
      public io.grpc.clockSync.ClockSync.resTimeObj getDefaultInstanceForType() {
        return io.grpc.clockSync.ClockSync.resTimeObj.getDefaultInstance();
      }

      @java.lang.Override
      public io.grpc.clockSync.ClockSync.resTimeObj build() {
        io.grpc.clockSync.ClockSync.resTimeObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.grpc.clockSync.ClockSync.resTimeObj buildPartial() {
        io.grpc.clockSync.ClockSync.resTimeObj result = new io.grpc.clockSync.ClockSync.resTimeObj(this);
        result.clientSentTime_ = clientSentTime_;
        result.serverRecdTime_ = serverRecdTime_;
        result.serverSentTime_ = serverSentTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.grpc.clockSync.ClockSync.resTimeObj) {
          return mergeFrom((io.grpc.clockSync.ClockSync.resTimeObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.grpc.clockSync.ClockSync.resTimeObj other) {
        if (other == io.grpc.clockSync.ClockSync.resTimeObj.getDefaultInstance()) return this;
        if (!other.getClientSentTime().isEmpty()) {
          clientSentTime_ = other.clientSentTime_;
          onChanged();
        }
        if (!other.getServerRecdTime().isEmpty()) {
          serverRecdTime_ = other.serverRecdTime_;
          onChanged();
        }
        if (!other.getServerSentTime().isEmpty()) {
          serverSentTime_ = other.serverSentTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.grpc.clockSync.ClockSync.resTimeObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.grpc.clockSync.ClockSync.resTimeObj) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object clientSentTime_ = "";
      /**
       * <code>string client_sent_time = 1;</code>
       */
      public java.lang.String getClientSentTime() {
        java.lang.Object ref = clientSentTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientSentTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string client_sent_time = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClientSentTimeBytes() {
        java.lang.Object ref = clientSentTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientSentTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client_sent_time = 1;</code>
       */
      public Builder setClientSentTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientSentTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client_sent_time = 1;</code>
       */
      public Builder clearClientSentTime() {
        
        clientSentTime_ = getDefaultInstance().getClientSentTime();
        onChanged();
        return this;
      }
      /**
       * <code>string client_sent_time = 1;</code>
       */
      public Builder setClientSentTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientSentTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object serverRecdTime_ = "";
      /**
       * <code>string server_recd_time = 2;</code>
       */
      public java.lang.String getServerRecdTime() {
        java.lang.Object ref = serverRecdTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serverRecdTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string server_recd_time = 2;</code>
       */
      public com.google.protobuf.ByteString
          getServerRecdTimeBytes() {
        java.lang.Object ref = serverRecdTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverRecdTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string server_recd_time = 2;</code>
       */
      public Builder setServerRecdTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverRecdTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string server_recd_time = 2;</code>
       */
      public Builder clearServerRecdTime() {
        
        serverRecdTime_ = getDefaultInstance().getServerRecdTime();
        onChanged();
        return this;
      }
      /**
       * <code>string server_recd_time = 2;</code>
       */
      public Builder setServerRecdTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverRecdTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object serverSentTime_ = "";
      /**
       * <code>string server_sent_time = 3;</code>
       */
      public java.lang.String getServerSentTime() {
        java.lang.Object ref = serverSentTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          serverSentTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string server_sent_time = 3;</code>
       */
      public com.google.protobuf.ByteString
          getServerSentTimeBytes() {
        java.lang.Object ref = serverSentTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverSentTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string server_sent_time = 3;</code>
       */
      public Builder setServerSentTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverSentTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string server_sent_time = 3;</code>
       */
      public Builder clearServerSentTime() {
        
        serverSentTime_ = getDefaultInstance().getServerSentTime();
        onChanged();
        return this;
      }
      /**
       * <code>string server_sent_time = 3;</code>
       */
      public Builder setServerSentTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverSentTime_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:resTimeObj)
    }

    // @@protoc_insertion_point(class_scope:resTimeObj)
    private static final io.grpc.clockSync.ClockSync.resTimeObj DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.grpc.clockSync.ClockSync.resTimeObj();
    }

    public static io.grpc.clockSync.ClockSync.resTimeObj getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<resTimeObj>
        PARSER = new com.google.protobuf.AbstractParser<resTimeObj>() {
      @java.lang.Override
      public resTimeObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new resTimeObj(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<resTimeObj> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<resTimeObj> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.grpc.clockSync.ClockSync.resTimeObj getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reqTimeObj_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reqTimeObj_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_resTimeObj_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_resTimeObj_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017clockSync.proto\"&\n\nreqTimeObj\022\030\n\020clien" +
      "t_sent_time\030\001 \001(\t\"Z\n\nresTimeObj\022\030\n\020clien" +
      "t_sent_time\030\001 \001(\t\022\030\n\020server_recd_time\030\002 " +
      "\001(\t\022\030\n\020server_sent_time\030\003 \001(\t2/\n\013TimeCom" +
      "pute\022 \n\004Time\022\013.reqTimeObj\032\013.resTimeObjB\023" +
      "\n\021io.grpc.clockSyncb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_reqTimeObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_reqTimeObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reqTimeObj_descriptor,
        new java.lang.String[] { "ClientSentTime", });
    internal_static_resTimeObj_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_resTimeObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_resTimeObj_descriptor,
        new java.lang.String[] { "ClientSentTime", "ServerRecdTime", "ServerSentTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
